/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author c.lorenzo2
 */
public class Gameplay extends javax.swing.JFrame {

    /**
     * Creates new form Gameplay
     */
    public Gameplay() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton41 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        Front1 = new javax.swing.JButton();
        Front2 = new javax.swing.JButton();
        Front3 = new javax.swing.JButton();
        Front4 = new javax.swing.JButton();
        Front5 = new javax.swing.JButton();
        Front6 = new javax.swing.JButton();
        Front7 = new javax.swing.JButton();
        Front8 = new javax.swing.JButton();
        Front9 = new javax.swing.JButton();
        Front10 = new javax.swing.JButton();
        Front11 = new javax.swing.JButton();
        Front12 = new javax.swing.JButton();
        Front13 = new javax.swing.JButton();
        Front14 = new javax.swing.JButton();
        Front15 = new javax.swing.JButton();
        Front16 = new javax.swing.JButton();
        Front17 = new javax.swing.JButton();
        Front18 = new javax.swing.JButton();
        Front19 = new javax.swing.JButton();
        Front20 = new javax.swing.JButton();
        Front21 = new javax.swing.JButton();
        Front22 = new javax.swing.JButton();
        Front23 = new javax.swing.JButton();
        Front24 = new javax.swing.JButton();
        Front25 = new javax.swing.JButton();
        Front26 = new javax.swing.JButton();
        Front27 = new javax.swing.JButton();
        Front28 = new javax.swing.JButton();
        Front29 = new javax.swing.JButton();
        Front30 = new javax.swing.JButton();
        Front31 = new javax.swing.JButton();
        Front32 = new javax.swing.JButton();
        Front33 = new javax.swing.JButton();
        Front34 = new javax.swing.JButton();
        Front35 = new javax.swing.JButton();
        Front36 = new javax.swing.JButton();
        Front37 = new javax.swing.JButton();
        Front38 = new javax.swing.JButton();
        Front39 = new javax.swing.JButton();
        Front40 = new javax.swing.JButton();
        Front41 = new javax.swing.JButton();
        Front42 = new javax.swing.JButton();
        Front43 = new javax.swing.JButton();
        Front44 = new javax.swing.JButton();
        Front45 = new javax.swing.JButton();
        Front46 = new javax.swing.JButton();
        Front47 = new javax.swing.JButton();
        Front48 = new javax.swing.JButton();
        Front49 = new javax.swing.JButton();
        Front50 = new javax.swing.JButton();
        Front51 = new javax.swing.JButton();
        Front52 = new javax.swing.JButton();
        Front53 = new javax.swing.JButton();
        Front54 = new javax.swing.JButton();
        Front55 = new javax.swing.JButton();
        Back1 = new javax.swing.JButton();
        Back2 = new javax.swing.JButton();
        Back3 = new javax.swing.JButton();
        Back4 = new javax.swing.JButton();
        Back5 = new javax.swing.JButton();
        Back6 = new javax.swing.JButton();
        Back7 = new javax.swing.JButton();
        Back8 = new javax.swing.JButton();
        Back9 = new javax.swing.JButton();
        Back10 = new javax.swing.JButton();
        Back11 = new javax.swing.JButton();
        Back12 = new javax.swing.JButton();
        Back13 = new javax.swing.JButton();
        Back14 = new javax.swing.JButton();
        Back15 = new javax.swing.JButton();
        Back16 = new javax.swing.JButton();
        Back17 = new javax.swing.JButton();
        Back18 = new javax.swing.JButton();
        Back19 = new javax.swing.JButton();
        Back20 = new javax.swing.JButton();
        Back21 = new javax.swing.JButton();
        Back22 = new javax.swing.JButton();
        Back23 = new javax.swing.JButton();
        Back24 = new javax.swing.JButton();
        Back25 = new javax.swing.JButton();
        Back26 = new javax.swing.JButton();
        Back27 = new javax.swing.JButton();
        Back28 = new javax.swing.JButton();
        Back29 = new javax.swing.JButton();
        Back30 = new javax.swing.JButton();
        Back31 = new javax.swing.JButton();
        Back32 = new javax.swing.JButton();
        Back33 = new javax.swing.JButton();
        Back34 = new javax.swing.JButton();
        Back35 = new javax.swing.JButton();
        Back36 = new javax.swing.JButton();
        Back37 = new javax.swing.JButton();
        Back38 = new javax.swing.JButton();
        Back39 = new javax.swing.JButton();
        Back40 = new javax.swing.JButton();
        Back41 = new javax.swing.JButton();
        Back42 = new javax.swing.JButton();
        Back43 = new javax.swing.JButton();
        Back44 = new javax.swing.JButton();
        Back45 = new javax.swing.JButton();
        Back46 = new javax.swing.JButton();
        Back47 = new javax.swing.JButton();
        Back48 = new javax.swing.JButton();
        Back49 = new javax.swing.JButton();
        Back50 = new javax.swing.JButton();
        Back51 = new javax.swing.JButton();
        Back52 = new javax.swing.JButton();
        Back53 = new javax.swing.JButton();
        Back54 = new javax.swing.JButton();
        Back55 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton41.setText("jButton41");

        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        jButton43.setText("jButton43");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });

        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        jButton51.setText("jButton51");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        jButton39.setText("jButton39");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });

        jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        jButton49.setText("jButton49");

        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        jButton42.setText("jButton42");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        jButton44.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\CS40S\\FinalProjevt\\src\\finalproject\\0.gif")); // NOI18N
        jButton44.setText("jButton44");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Front1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalprojevt/0.gif"))); // NOI18N
        Front1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front1ActionPerformed(evt);
            }
        });
        getContentPane().add(Front1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 101, 136));

        Front2.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front2ActionPerformed(evt);
            }
        });
        getContentPane().add(Front2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 101, 136));

        Front3.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front3ActionPerformed(evt);
            }
        });
        getContentPane().add(Front3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 101, 136));

        Front4.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front4ActionPerformed(evt);
            }
        });
        getContentPane().add(Front4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 101, 140));

        Front5.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front5ActionPerformed(evt);
            }
        });
        getContentPane().add(Front5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 101, 136));

        Front6.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front6ActionPerformed(evt);
            }
        });
        getContentPane().add(Front6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 101, 136));

        Front7.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front7ActionPerformed(evt);
            }
        });
        getContentPane().add(Front7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 101, 136));

        Front8.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front8ActionPerformed(evt);
            }
        });
        getContentPane().add(Front8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 101, 136));

        Front9.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 101, 136));

        Front10.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 101, 136));

        Front11.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 101, 136));

        Front12.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front12ActionPerformed(evt);
            }
        });
        getContentPane().add(Front12, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 153, 101, 138));

        Front13.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front13, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 153, 101, 136));

        Front14.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front14ActionPerformed(evt);
            }
        });
        getContentPane().add(Front14, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 153, 101, 136));

        Front15.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 101, 136));

        Front16.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front16ActionPerformed(evt);
            }
        });
        getContentPane().add(Front16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 101, 136));

        Front17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front17, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 153, 101, 136));

        Front18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalprojevt/0.gif"))); // NOI18N
        getContentPane().add(Front18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 101, 136));

        Front19.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 101, 136));

        Front20.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 101, 136));

        Front21.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front21ActionPerformed(evt);
            }
        });
        getContentPane().add(Front21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 101, 136));

        Front22.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        getContentPane().add(Front22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, 101, 136));

        Front23.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front23ActionPerformed(evt);
            }
        });
        getContentPane().add(Front23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 101, 136));

        Front24.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front24ActionPerformed(evt);
            }
        });
        getContentPane().add(Front24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 101, 136));

        Front25.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front25ActionPerformed(evt);
            }
        });
        getContentPane().add(Front25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 101, 136));

        Front26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front26ActionPerformed(evt);
            }
        });
        getContentPane().add(Front26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 101, 136));

        Front27.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\0.gif")); // NOI18N
        Front27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front27ActionPerformed(evt);
            }
        });
        getContentPane().add(Front27, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 300, 101, 136));

        Front28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 101, 136));

        Front29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front29, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 101, 136));

        Front30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front30ActionPerformed(evt);
            }
        });
        getContentPane().add(Front30, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 300, 101, 136));

        Front31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front31, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 300, 101, 136));

        Front32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front32ActionPerformed(evt);
            }
        });
        getContentPane().add(Front32, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 300, 101, 136));

        Front33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 300, 101, 136));

        Front34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front34ActionPerformed(evt);
            }
        });
        getContentPane().add(Front34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 448, 101, 136));

        Front35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front35ActionPerformed(evt);
            }
        });
        getContentPane().add(Front35, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 448, 101, 136));

        Front36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front36, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 448, 101, 136));

        Front37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front37ActionPerformed(evt);
            }
        });
        getContentPane().add(Front37, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 448, 101, 136));

        Front38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front38, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 448, 101, 136));

        Front39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front39, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 101, 136));

        Front40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front40ActionPerformed(evt);
            }
        });
        getContentPane().add(Front40, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 448, 101, 136));

        Front41.setIcon(new javax.swing.ImageIcon("C:\\Users\\c.lorenzo2\\Desktop\\CS40S\\FinalProjevt\\src\\finalproject\\0.gif")); // NOI18N
        Front41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front41ActionPerformed(evt);
            }
        });
        getContentPane().add(Front41, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 448, 101, 136));

        Front42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front42, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 448, 101, 136));

        Front43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front43, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 448, 101, 136));

        Front44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front44ActionPerformed(evt);
            }
        });
        getContentPane().add(Front44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 448, 101, 136));

        Front45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 592, 101, 136));

        Front46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front46, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 592, 101, 136));

        Front47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front47, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 592, 101, 136));

        Front48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front48, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 592, 101, 136));

        Front49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front49, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 592, 101, 136));

        Front50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front50ActionPerformed(evt);
            }
        });
        getContentPane().add(Front50, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 592, 101, 136));

        Front51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front51, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 592, 101, 136));

        Front52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        getContentPane().add(Front52, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 592, 101, 136));

        Front53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front53ActionPerformed(evt);
            }
        });
        getContentPane().add(Front53, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 592, 101, 136));

        Front54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front54ActionPerformed(evt);
            }
        });
        getContentPane().add(Front54, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 592, 101, 136));

        Front55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/0.gif"))); // NOI18N
        Front55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Front55ActionPerformed(evt);
            }
        });
        getContentPane().add(Front55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 592, 101, 136));

        Back1.setText("jButton65");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        getContentPane().add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 101, 136));

        Back2.setText("jButton1");
        Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2ActionPerformed(evt);
            }
        });
        getContentPane().add(Back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 130));

        Back3.setText("jButton1");
        getContentPane().add(Back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 101, 136));

        Back4.setText("jButton2");
        getContentPane().add(Back4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 101, 136));

        Back5.setText("jButton1");
        Back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back5ActionPerformed(evt);
            }
        });
        getContentPane().add(Back5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 101, 130));

        Back6.setText("jButton2");
        getContentPane().add(Back6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 101, 136));

        Back7.setText("jButton3");
        getContentPane().add(Back7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 101, 136));

        Back8.setText("jButton4");
        Back8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back8ActionPerformed(evt);
            }
        });
        getContentPane().add(Back8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 100, 130));

        Back9.setText("jButton5");
        getContentPane().add(Back9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 100, 130));

        Back10.setText("jButton6");
        getContentPane().add(Back10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 101, 136));

        Back11.setText("jButton7");
        getContentPane().add(Back11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 101, 136));

        Back12.setText("jButton1");
        Back12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back12ActionPerformed(evt);
            }
        });
        getContentPane().add(Back12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 101, 140));

        Back13.setText("jButton2");
        getContentPane().add(Back13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 159, 100, 130));

        Back14.setText("jButton3");
        getContentPane().add(Back14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 156, 90, 130));

        Back15.setText("jButton4");
        Back15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back15ActionPerformed(evt);
            }
        });
        getContentPane().add(Back15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 101, 136));

        Back16.setText("jButton5");
        getContentPane().add(Back16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 101, 136));

        Back17.setText("jButton6");
        getContentPane().add(Back17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 101, 136));

        Back18.setText("jButton7");
        getContentPane().add(Back18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 101, 136));

        Back19.setText("jButton8");
        getContentPane().add(Back19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 101, 136));

        Back20.setText("jButton9");
        getContentPane().add(Back20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 101, 136));

        Back21.setText("jButton10");
        Back21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back21ActionPerformed(evt);
            }
        });
        getContentPane().add(Back21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 101, 136));

        Back22.setText("jButton11");
        getContentPane().add(Back22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, 101, 136));

        Back23.setText("jButton1");
        getContentPane().add(Back23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 101, 136));

        Back24.setText("jButton2");
        getContentPane().add(Back24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 101, 136));

        Back25.setText("jButton3");
        getContentPane().add(Back25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 101, 136));

        Back26.setText("jButton4");
        getContentPane().add(Back26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 101, 136));

        Back27.setText("jButton5");
        getContentPane().add(Back27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 101, 136));

        Back28.setText("jButton6");
        getContentPane().add(Back28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 101, 136));

        Back29.setText("jButton7");
        getContentPane().add(Back29, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 101, 136));

        Back30.setText("jButton8");
        getContentPane().add(Back30, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 101, 136));

        Back31.setText("jButton9");
        getContentPane().add(Back31, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 101, 136));

        Back32.setText("jButton10");
        getContentPane().add(Back32, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 101, 136));

        Back33.setText("jButton11");
        Back33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back33ActionPerformed(evt);
            }
        });
        getContentPane().add(Back33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 300, 100, 130));

        Back34.setText("jButton12");
        getContentPane().add(Back34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 101, 136));

        Back35.setText("jButton13");
        getContentPane().add(Back35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 101, 136));

        Back36.setText("jButton14");
        getContentPane().add(Back36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 101, 136));

        Back37.setText("jButton15");
        getContentPane().add(Back37, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 101, 136));

        Back38.setText("jButton16");
        getContentPane().add(Back38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 101, 136));

        Back39.setText("jButton17");
        getContentPane().add(Back39, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 101, 136));

        Back40.setText("jButton18");
        getContentPane().add(Back40, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 101, 136));

        Back41.setText("jButton19");
        getContentPane().add(Back41, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 101, 136));

        Back42.setText("jButton20");
        getContentPane().add(Back42, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 101, 136));

        Back43.setText("jButton21");
        getContentPane().add(Back43, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 101, 136));

        Back44.setText("jButton22");
        getContentPane().add(Back44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 450, 101, 136));

        Back45.setText("jButton23");
        getContentPane().add(Back45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 101, 136));

        Back46.setText("jButton24");
        getContentPane().add(Back46, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 101, 136));

        Back47.setText("jButton25");
        getContentPane().add(Back47, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 101, 136));

        Back48.setText("jButton26");
        getContentPane().add(Back48, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 101, 136));

        Back49.setText("jButton27");
        getContentPane().add(Back49, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 101, 136));

        Back50.setText("jButton28");
        Back50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back50ActionPerformed(evt);
            }
        });
        getContentPane().add(Back50, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 101, 136));

        Back51.setText("jButton29");
        Back51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back51ActionPerformed(evt);
            }
        });
        getContentPane().add(Back51, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 101, 136));

        Back52.setText("jButton30");
        Back52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back52ActionPerformed(evt);
            }
        });
        getContentPane().add(Back52, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 101, 136));

        Back53.setText("jButton31");
        getContentPane().add(Back53, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 101, 136));

        Back54.setText("jButton32");
        Back54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back54ActionPerformed(evt);
            }
        });
        getContentPane().add(Back54, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, 101, 136));

        Back55.setText("jButton33");
        Back55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back55ActionPerformed(evt);
            }
        });
        getContentPane().add(Back55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 590, 101, 136));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void Front1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front1ActionPerformed
         Front1.setVisible(false);
    }//GEN-LAST:event_Front1ActionPerformed

    private void Front23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front23ActionPerformed
        Front23.setVisible(false);
    }//GEN-LAST:event_Front23ActionPerformed

    private void Front16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front16ActionPerformed
        Front16.setVisible(false);
    }//GEN-LAST:event_Front16ActionPerformed

    private void Front24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front24ActionPerformed
        Front24.setVisible(false);
    }//GEN-LAST:event_Front24ActionPerformed

    private void Front25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front25ActionPerformed
       Front25.setVisible(false);
    }//GEN-LAST:event_Front25ActionPerformed

    private void Front14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front14ActionPerformed
        Front14.setVisible(false);
    }//GEN-LAST:event_Front14ActionPerformed

    private void Front26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front26ActionPerformed
        Front26.setVisible(false);
    }//GEN-LAST:event_Front26ActionPerformed

    private void Front44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front44ActionPerformed
        Front44.setVisible(false);
    }//GEN-LAST:event_Front44ActionPerformed

    private void Front5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front5ActionPerformed
        Front5.setVisible(false);
    }//GEN-LAST:event_Front5ActionPerformed

    private void Front7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front7ActionPerformed
       Front7.setVisible(false);
    }//GEN-LAST:event_Front7ActionPerformed

    private void Front21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front21ActionPerformed
      Front21.setVisible(false);
    }//GEN-LAST:event_Front21ActionPerformed

    private void Front35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front35ActionPerformed
       Front35.setVisible(false);
    }//GEN-LAST:event_Front35ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        Front42.setVisible(false);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        Front51.setVisible(false);
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        Front39.setVisible(false);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
      Front39.setVisible(false);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        Front48.setVisible(false);
    }//GEN-LAST:event_jButton48ActionPerformed

    private void Front41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front41ActionPerformed
        Front41.setVisible(false);
    }//GEN-LAST:event_Front41ActionPerformed

    private void Front30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front30ActionPerformed
        Front30.setVisible(false);
    }//GEN-LAST:event_Front30ActionPerformed

    private void Front32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front32ActionPerformed
        Front32.setVisible(false);

    }//GEN-LAST:event_Front32ActionPerformed

    private void Front37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front37ActionPerformed
         Front37.setVisible(false);
    }//GEN-LAST:event_Front37ActionPerformed

    private void Front50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front50ActionPerformed
       Front50.setVisible(false);
    }//GEN-LAST:event_Front50ActionPerformed

    private void Front53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front53ActionPerformed
         Front53.setVisible(false);
    }//GEN-LAST:event_Front53ActionPerformed

    private void Front34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front34ActionPerformed
         Front34.setVisible(false);
    }//GEN-LAST:event_Front34ActionPerformed

    private void Front12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front12ActionPerformed
       Front12.setVisible(false);
    }//GEN-LAST:event_Front12ActionPerformed

    private void Front27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front27ActionPerformed
        Front27.setVisible(false);
    }//GEN-LAST:event_Front27ActionPerformed

    private void Front55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front55ActionPerformed
        Front55.setVisible(false);
    }//GEN-LAST:event_Front55ActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
         
    }//GEN-LAST:event_Back1ActionPerformed

    private void Front40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front40ActionPerformed
         Front40.setVisible(false);
    }//GEN-LAST:event_Front40ActionPerformed

    private void Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back2ActionPerformed

    private void Back12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back12ActionPerformed

    private void Back21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back21ActionPerformed

    private void Back50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back50ActionPerformed

    private void Back51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back51ActionPerformed

    private void Back52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back52ActionPerformed

    private void Back54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back54ActionPerformed

    private void Back55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back55ActionPerformed

    private void Front54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front54ActionPerformed
         Front54.setVisible(false);
    }//GEN-LAST:event_Front54ActionPerformed

    private void Front2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front2ActionPerformed
       Front2.setVisible(false);
    }//GEN-LAST:event_Front2ActionPerformed

    private void Front3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front3ActionPerformed
         Front3.setVisible(false);
    }//GEN-LAST:event_Front3ActionPerformed

    private void Front4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front4ActionPerformed
         Front4.setVisible(false);
    }//GEN-LAST:event_Front4ActionPerformed

    private void Front6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front6ActionPerformed
         Front6.setVisible(false);
    }//GEN-LAST:event_Front6ActionPerformed

    private void Back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back5ActionPerformed

    private void Back33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back33ActionPerformed

    private void Back15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back15ActionPerformed

    private void Front8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Front8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Front8ActionPerformed

    private void Back8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gameplay().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JButton Back10;
    private javax.swing.JButton Back11;
    private javax.swing.JButton Back12;
    private javax.swing.JButton Back13;
    private javax.swing.JButton Back14;
    private javax.swing.JButton Back15;
    private javax.swing.JButton Back16;
    private javax.swing.JButton Back17;
    private javax.swing.JButton Back18;
    private javax.swing.JButton Back19;
    private javax.swing.JButton Back2;
    private javax.swing.JButton Back20;
    private javax.swing.JButton Back21;
    private javax.swing.JButton Back22;
    private javax.swing.JButton Back23;
    private javax.swing.JButton Back24;
    private javax.swing.JButton Back25;
    private javax.swing.JButton Back26;
    private javax.swing.JButton Back27;
    private javax.swing.JButton Back28;
    private javax.swing.JButton Back29;
    private javax.swing.JButton Back3;
    private javax.swing.JButton Back30;
    private javax.swing.JButton Back31;
    private javax.swing.JButton Back32;
    private javax.swing.JButton Back33;
    private javax.swing.JButton Back34;
    private javax.swing.JButton Back35;
    private javax.swing.JButton Back36;
    private javax.swing.JButton Back37;
    private javax.swing.JButton Back38;
    private javax.swing.JButton Back39;
    private javax.swing.JButton Back4;
    private javax.swing.JButton Back40;
    private javax.swing.JButton Back41;
    private javax.swing.JButton Back42;
    private javax.swing.JButton Back43;
    private javax.swing.JButton Back44;
    private javax.swing.JButton Back45;
    private javax.swing.JButton Back46;
    private javax.swing.JButton Back47;
    private javax.swing.JButton Back48;
    private javax.swing.JButton Back49;
    private javax.swing.JButton Back5;
    private javax.swing.JButton Back50;
    private javax.swing.JButton Back51;
    private javax.swing.JButton Back52;
    private javax.swing.JButton Back53;
    private javax.swing.JButton Back54;
    private javax.swing.JButton Back55;
    private javax.swing.JButton Back6;
    private javax.swing.JButton Back7;
    private javax.swing.JButton Back8;
    private javax.swing.JButton Back9;
    private javax.swing.JButton Front1;
    private javax.swing.JButton Front10;
    private javax.swing.JButton Front11;
    private javax.swing.JButton Front12;
    private javax.swing.JButton Front13;
    private javax.swing.JButton Front14;
    private javax.swing.JButton Front15;
    private javax.swing.JButton Front16;
    private javax.swing.JButton Front17;
    private javax.swing.JButton Front18;
    private javax.swing.JButton Front19;
    private javax.swing.JButton Front2;
    private javax.swing.JButton Front20;
    private javax.swing.JButton Front21;
    private javax.swing.JButton Front22;
    private javax.swing.JButton Front23;
    private javax.swing.JButton Front24;
    private javax.swing.JButton Front25;
    private javax.swing.JButton Front26;
    private javax.swing.JButton Front27;
    private javax.swing.JButton Front28;
    private javax.swing.JButton Front29;
    private javax.swing.JButton Front3;
    private javax.swing.JButton Front30;
    private javax.swing.JButton Front31;
    private javax.swing.JButton Front32;
    private javax.swing.JButton Front33;
    private javax.swing.JButton Front34;
    private javax.swing.JButton Front35;
    private javax.swing.JButton Front36;
    private javax.swing.JButton Front37;
    private javax.swing.JButton Front38;
    private javax.swing.JButton Front39;
    private javax.swing.JButton Front4;
    private javax.swing.JButton Front40;
    private javax.swing.JButton Front41;
    private javax.swing.JButton Front42;
    private javax.swing.JButton Front43;
    private javax.swing.JButton Front44;
    private javax.swing.JButton Front45;
    private javax.swing.JButton Front46;
    private javax.swing.JButton Front47;
    private javax.swing.JButton Front48;
    private javax.swing.JButton Front49;
    private javax.swing.JButton Front5;
    private javax.swing.JButton Front50;
    private javax.swing.JButton Front51;
    private javax.swing.JButton Front52;
    private javax.swing.JButton Front53;
    private javax.swing.JButton Front54;
    private javax.swing.JButton Front55;
    private javax.swing.JButton Front6;
    private javax.swing.JButton Front7;
    private javax.swing.JButton Front8;
    private javax.swing.JButton Front9;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton51;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
